feat(sse): enable for production
SolidStateGroup/bullet-train-api pull request #1506
Opened 2022-10-06 12:06 UTC by gagantrivedi

Thanks for submitting a PR! Please check the boxes below:

- [ ] I have run [`pre-commit`](https://docs.flagsmith.com/deployment/locally-api#pre-commit) to check linting
- [ ] I have filled in the "Changes" section below?
- [ ] I have filled in the "How did you test this code" section below?

## Changes
Add environment variables to enable edge for production

## How did you test this code?

*Please describe.*

2022-10-06 12:07 UTC, gagantrivedi commented
Depends on SSE_AUTHENTICATION_TOKEN secret being present

2022-10-06 12:21 UTC, dabeeeenster approved these changes

2022-10-10 11:39 UTC, dabeeeenster approved these changes

2022-10-12 11:39 UTC, matthewelwell requested changes

2022-10-12 11:39 UTC, matthewelwell commented on infrastructure/aws/production/ecs-task-definition-web.json
> +                    "name": "ENABLE_TASK_PROCESSOR_HEALTH_CHECK",
Can you remove this please? Not sure why it has been re-added in this PR?

2022-10-12 11:50 UTC, gagantrivedi commented on infrastructure/aws/production/ecs-task-definition-web.json
> +                    "name": "ENABLE_TASK_PROCESSOR_HEALTH_CHECK",
Ugh, yeah, bad rebase.

2022-10-12 13:20 UTC, matthewelwell approved these changes

2022-10-13 04:46 UTC, merged