improvement/fix-image-tags-in-docker
SolidStateGroup/bullet-train-api pull request #1679
Opened 2022-11-21 18:41 UTC by dabeeeenster

2022-11-21 18:46 UTC, matthewelwell approved these changes

2022-11-22 09:07 UTC, matthewelwell requested changes

2022-11-22 09:07 UTC, matthewelwell commented on .github/workflows/frontend-e2e-docker-publish-image.yml
> +                      flagsmith/flagsmith-frontend
This should be `flagsmith/flagsmith-e2e-tests` I think?

2022-11-22 09:15 UTC, dabeeeenster commented on .github/workflows/frontend-e2e-docker-publish-image.yml
> +                      flagsmith/flagsmith-frontend
Hmmm yes but maybe do that in a different PR?

2022-11-22 09:19 UTC, matthewelwell commented on .github/workflows/frontend-e2e-docker-publish-image.yml
> +                      flagsmith/flagsmith-frontend
Why? We've essentially broken this workflow in this PR.

2022-11-22 09:45 UTC, dabeeeenster commented on .github/workflows/frontend-e2e-docker-publish-image.yml
> +                      flagsmith/flagsmith-frontend
Oops sorry I misread the diff. Fixed.

2022-11-22 10:01 UTC, matthewelwell approved these changes

2022-11-24 11:54 UTC, merged