Prevent deleted API keys from being returned
SolidStateGroup/bullet-train-api pull request #2182
Opened 2023-05-04 11:28 UTC by matthewelwell

## Changes

Ensures that deleted MasterAPIKeys are not returned by the viewset after being deleted. 

## How did you test this code?

Added a new integration test.

2023-05-15 14:38 UTC, khvn26 approved these changes

2023-05-15 14:38 UTC, khvn26 commented on api/tests/integration/api_keys/test_viewset.py
> +    admin_client, organisation, master_api_key, master_api_key_client
nit: typing

2023-05-15 16:00 UTC, matthewelwell commented on api/tests/integration/api_keys/test_viewset.py
> +    admin_client, organisation, master_api_key, master_api_key_client
Good point - have added.

2023-05-18 08:31 UTC, khvn26 requested changes

2023-05-18 08:31 UTC, khvn26 commented on api/tests/integration/api_keys/test_viewset.py
> +    master_api_key: dict,
```suggestion
    master_api_key: typing.Tuple["AbstractAPIKey", str],
```

2023-05-18 08:31 UTC, khvn26 commented on api/tests/integration/api_keys/test_viewset.py
> +):
```suggestion
) -> None:
```

2023-06-09 09:24 UTC, matthewelwell commented on api/tests/integration/api_keys/test_viewset.py
> +):
I'm not sure I agree that we should add the return type to all of our tests? I think that `None` is assumed to be the default return type, and we can be fairly confident that all test functions / methods have no return type. Happy to discuss this further though if you have a strong opinion on this.

2023-06-09 09:32 UTC, khvn26 commented on api/tests/integration/api_keys/test_viewset.py
> +):
I would agree with you if omitting a return type would mean an implicit `None`. Unfortunately, it means implicit `Any` , so even obvious cases like tests and `__init__` methods have to be annotated if we want to come to a fully typed project in the future.

2023-06-15 10:26 UTC, khvn26 approved these changes

2023-06-15 10:28 UTC, merged