fix(sentry): Add sampler to fuction to block /health transactions
SolidStateGroup/bullet-train-api pull request #232
Opened 2021-07-30 08:39 UTC by gagantrivedi

2021-07-30 12:49 UTC, matthewelwell commented on api/integrations/sentry/apps.py
> +def traces_sampler(ctx):
I'm not a massive fan of this being defined in the `apps` module. Could we move it somewhere more appropriate? `samplers` or something?

2021-08-02 08:32 UTC, matthewelwell requested changes

2021-08-02 08:32 UTC, matthewelwell commented on api/integrations/sentry/samplers.py
> +def block_health_sampler(ctx):
Could we add a unit test for this now?

2021-08-02 12:16 UTC, dabeeeenster commented
Actually sorry @gagantrivedi but this needs to move out of the `integrations/sentry` area altogether. There are 2 ways Flagsmith uses sentry:

1. As an APM for the API itself. This PR is related to that. 
2. For customers of the platform to send flag change events into *their* sentry installation. This is what `integrations/sentry` is for. 

I think this code should live in `app` - what do you think @matthewelwell ?

2021-08-02 12:19 UTC, matthewelwell commented
I don't really see any reason why it needs to move out of the `sentry` package tbh? It's still code related to Sentry, it's just that there are multiple ways in which we use Sentry.

2021-08-02 12:23 UTC, dabeeeenster commented
OK lets leave it here - but add that test pls @gagantrivedi

2021-08-02 12:37 UTC, gagantrivedi commented
> OK lets leave it here - but add that test pls @gagantrivedi

Sure, but is this working for you locally? i.e: can you see transaction generated locally on the sentry dashboard?

2021-08-02 12:38 UTC, dabeeeenster commented
Yes - transactions other than /health show up

2021-08-03 08:52 UTC, matthewelwell requested changes

2021-08-03 08:52 UTC, matthewelwell commented on api/integrations/sentry/tests/test_sampler.py
> +    settings.SENTRY_TRACE_SAMPLE_RATE = 10
It's better to use the `@override_settings()` decorator to do this so your tests become something like the following: 

```python
sample_rate = 10

@override_settings(SENTRY_TRACE_SAMPLE_RATE=sample_rate)
def test_block_health_sampler_empty_context_returns_defaut_sample_rate():
    assert block_health_sampler({}) == sample_rate
```

See documentation here: https://docs.djangoproject.com/en/3.2/topics/testing/tools/#django.test.override_settings

2021-08-03 09:22 UTC, matthewelwell approved these changes
Some minor changes so that we're reusing the variable we defined as much as possible.

2021-08-03 09:22 UTC, matthewelwell commented on api/integrations/sentry/tests/test_sampler.py
> +    assert sample_rate == 10
```suggestion
    assert sample_rate == SAMPLE_RATE
```

2021-08-03 09:22 UTC, matthewelwell commented on api/integrations/sentry/tests/test_sampler.py
> +    assert sample_rate == 10
```suggestion
    assert sample_rate == SAMPLE_RATE
```

2021-08-03 09:25 UTC, merged