fix: Feature id in mv-option request is undefined
SolidStateGroup/bullet-train-api pull request #2751
Opened 2023-09-06 22:18 UTC by novakzaballa

Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- The feature ID is no longer undefined.
- It is validated that the feature ID is in the request.

## How did you test this code?

- Create a new MV feature.

2023-09-07 15:08 UTC, matthewelwell requested changes

2023-09-07 15:08 UTC, matthewelwell commented on api/features/multivariate/views.py
> +            raise ValidationError("Feature Id cannot be undefined or is nonexistent.")
This will have no effect here. The issue is when creating an MV feature option which doesn't use `get_queryset`. I recommend writing a test to cover the issue.

2023-09-11 08:23 UTC, matthewelwell requested changes

2023-09-11 08:23 UTC, matthewelwell commented on api/features/multivariate/views.py
> +            )
We shouldn't only check for `"undefined"` here. What about other invalid ids? Or ids of features from projects the user doesn't belong to?

2023-09-12 14:06 UTC, matthewelwell commented on api/features/multivariate/views.py
> +        get_object_or_404(Feature, pk=feature_pk)
This still isn't checking that it's a project they belong to.

2023-09-12 14:06 UTC, matthewelwell commented on api/features/multivariate/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
```suggestion
        return super().create(request, *args, **kwargs
```

2023-09-12 16:55 UTC, novakzaballa commented on api/features/multivariate/views.py
> +        get_object_or_404(Feature, pk=feature_pk)
Is this being checked here, right?https://github.com/Flagsmith/flagsmith/blob/d2ff80e79ebbc653d5b398134d333c89f03c4042/api/features/multivariate/views.py#L21

2023-09-12 16:55 UTC, novakzaballa commented on api/features/multivariate/views.py
> +        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
Corrected.

2023-09-12 16:57 UTC, matthewelwell commented on api/features/multivariate/views.py
> +        get_object_or_404(Feature, pk=feature_pk)
No, looks like that is checking they have permissions on the project. So it should be sufficient to change this to:

```python
feature_pk = self.kwargs.get("feature_pk")
project_pk = self.kwargs.get("project_pk")
get_object_or_404(Feature.objects.filter(project__id=project_pk), pk=feature_pk)
```

2023-09-12 17:29 UTC, novakzaballa commented on api/features/multivariate/views.py
> +        get_object_or_404(Feature, pk=feature_pk)
Now I understand what you meant, Thank you, corrected.

2023-09-12 17:31 UTC, matthewelwell approved these changes

2023-09-12 20:43 UTC, merged