chore: use Depot for flagsmith-api image build
SolidStateGroup/bullet-train-api pull request #3179
Opened 2023-12-18 18:21 UTC by khvn26

Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [ ] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

This makes the `flagsmith-api` image builds to be run by Depot.

## How did you test this code?

Tested in the initial PR (https://github.com/Flagsmith/flagsmith/pull/3071).
`flagsmith-api` image should be pushed by Depot in CI.

2023-12-18 18:23 UTC, matthewelwell approved these changes

2023-12-18 19:28 UTC, matthewelwell requested changes
Actually, I think this might be missing the permissions? 

```yaml
    permissions:
      id-token: write
      contents: read
```

2023-12-18 19:57 UTC, dabeeeenster reviewed
Isnt this missing

```
        uses: depot/build-push-action@v1
        with:
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          project: qsrts2l4gr

```
etc?

2023-12-19 10:23 UTC, matthewelwell approved these changes

2023-12-19 10:26 UTC, merged