feat: redesign organisation layout
SolidStateGroup/bullet-train-api pull request #3257
Opened 2024-01-09 14:06 UTC by azaiko-akveo

Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Apply new design to organization management functionality

## How did you test this code?

Test application locally

2024-01-10 11:29 UTC, dabeeeenster commented
Can we fix the layout shifting as per the screen recording


https://github.com/Flagsmith/flagsmith/assets/173290/48cbcf38-01f8-4f8f-859a-273ee8c131d4

2024-01-10 15:10 UTC, azaiko-akveo commented
> Can we fix the layout shifting as per the screen recording

The shift occurs due to hiding/displaying the global application scrollbar.
The effect doesn't exist for most recent browser versions (verified for Chrome, Firefox, and Safari).

To resolve this issue, we need to update the global application layout styles. It will take significant time and considers testing all existing pages to handle unexpected issues.

2024-01-10 15:52 UTC, kyle-ssg commented
Upon logging in I see the following with no ability to change organisation. I suspect that we haven't considered permissions / viewing organisations as non admins ?

This needs to be tested with the following permissions

- Org admin
- Non org admin
- Non org admin but with Manage user groups / Manage users permissions

![image](https://github.com/Flagsmith/flagsmith/assets/8608314/b17dc3fd-062b-4e7c-8cc9-700f281c7d08)

2024-01-11 07:45 UTC, azaiko-akveo commented
> Upon logging in I see the following with no ability to change organisation. I suspect that we haven't considered permissions / viewing organisations as non admins ?
> 
> This needs to be tested with the following permissions
> 
> * Org admin
> * Non org admin
> * Non org admin but with Manage user groups / Manage users permissions
> 
> ![image](https://private-user-images.githubusercontent.com/8608314/295624575-b17dc3fd-062b-4e7c-8cc9-700f281c7d08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTgzNDQsIm5iZiI6MTcwNDk1ODA0NCwicGF0aCI6Ii84NjA4MzE0LzI5NTYyNDU3NS1iMTdkYzNmZC0wNjJiLTRlN2MtOGNjOS03MDBmMjgxYzdkMDgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTFUMDcyNzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzc1NmI4MzA3MzFiNjdjNjUyZGNiZjg3MWVhMmU2ZTE1ZDgxYWJmZDU0OTI1NDEyMTkzNmM2OTdkNTE1ZjQzMCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._UzNWoxRH3S4hk-Oi4nxLmZ2nkETkivbe13h-wlXXyo)

Fixed. Now it is possible to choose an organization if user doesn't have permissions

<img width="930" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/102226752/bd4b4624-b245-4229-bd2d-0af9cb42985c">

2024-01-11 13:13 UTC, kyle-ssg commented
@azaiko-akveo I can switch org now but I can't do what I previously could?

After: 

<img width="1511" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/8608314/97b357cc-ed0a-4678-b699-198ba6494d11">


Previously: 

Note: I can select a project to view.

<img width="1159" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/8608314/d6be7243-2327-4534-8ef0-aece879661af">


Please check that you can perform the same actions that you can on staging.flagsmith.com.

Also as mentioned, please check this with Manage user groups / Manage users permissions

2024-01-16 12:26 UTC, dabeeeenster commented
@azaiko-akveo can we get an update?

2024-01-16 12:56 UTC, azaiko-akveo commented
> an we get an update?

I'm still in the process of applying the logic of permissions

2024-01-16 13:10 UTC, dabeeeenster commented
> > an we get an update?
> 
> still in the process of applying the logic of permissions

Thanks for the update

2024-01-17 08:53 UTC, azaiko-akveo commented
@dabeeeenster , @kyle-ssg.
Permissions logic was updated. The PR is ready for review

2024-01-18 09:46 UTC, dabeeeenster commented
If I'm on the "Keys" tab, and change organisation using the dropdown, the Keys area doesnt update. Similar issues with Webhooks.

2024-01-18 14:11 UTC, azaiko-akveo commented
> @azaiko-akveo If I'm on the "Keys" tab, and change organisation using the dropdown, the Keys area doesnt update. Similar issues with Webhooks.

fixed

2024-01-19 12:04 UTC, kyle-ssg commented on frontend/web/components/ProjectManageWidget.tsx
> +                              <Permission
Since this a functional component now, can we replace the <Permission components with the equivelent useHasPermission

2024-01-19 12:05 UTC, kyle-ssg commented on frontend/web/components/ProjectManageWidget.tsx
> +        {({ isLoading, projects }: OrganisationContext) => (
I think we can replace this with the useProjects hook

2024-01-19 12:08 UTC, kyle-ssg requested changes
Just a couple comments

2024-01-19 13:43 UTC, azaiko-akveo commented
> Just a couple comments

@kyle-ssg , code was updated

2024-01-23 17:22 UTC, kyle-ssg commented
@azaiko-akveo When I click on the flagsmith logo it goes to /projects which looks just like the organisation link except without tabs. Is there a need for /projects? It doesn't seem useful

2024-01-23 17:50 UTC, dabeeeenster commented
It should redirect to the new projects tab in the org screen?

2024-01-23 17:59 UTC, kyle-ssg commented
After discussion, let's just remove the logo from the nav so that we have the following @azaiko-akveo 
![image](https://github.com/Flagsmith/flagsmith/assets/8608314/eda19e35-2108-4ee5-8138-9998ff79307d)

2024-01-24 13:26 UTC, azaiko-akveo commented
@kyle-ssg , @dabeeeenster 
* there is a case when user has access only for reading projects. To avoid displaying single tab we display the saparate page. The same behaviour currently exists for `/organisation-groups`
* the `/projects` is used in many other components withing the app including login functionality

2024-01-24 13:36 UTC, azaiko-akveo commented
> It should redirect to the new projects tab in the org screen?

Yes, if we need to keep existing application behaviour

2024-01-24 18:29 UTC, kyle-ssg approved these changes

2024-01-24 18:29 UTC, merged