fix(webhooks): prevent raise on give up
SolidStateGroup/bullet-train-api pull request #3295
Opened 2024-01-14 19:39 UTC by matthewelwell

## Changes

Prevent the code from raising the exception on give up off the backoff logic. Should resolve [this sentry issue](https://flagsmith.sentry.io/issues/4848505909). 

## How did you test this code?

I technically haven't but it seems like a sensible change and only adds a single kwarg to an existing decorator.

2024-01-15 09:30 UTC, khvn26 approved these changes

2024-01-15 09:31 UTC, khvn26 requested changes
```
TypeError: expo() got an unexpected keyword argument 'raise_on_giveup'
```

2024-01-15 09:43 UTC, matthewelwell commented
> ```
> TypeError: expo() got an unexpected keyword argument 'raise_on_giveup'
> ```

Whoops, looks like it's only available since 2.0 which something in our deps graph is preventing. I'll fix this up. Sorry!

2024-01-15 13:55 UTC, zachaysan approved these changes
It took me a double take to understand how the test works, but it looks good.

2024-01-15 15:56 UTC, matthewelwell commented
> It took me a double take to understand how the test works, but it looks good.

This seems fair on my own review so I've tried to add a bit more verbiage in the test to help clarify.

2024-01-16 09:15 UTC, matthewelwell commented on api/integrations/rudderstack/rudderstack.py
> +        rudder_analytics.dataPlaneUrl = config.base_url
This was a change in v2 of the rudderstack library. It blows my mind that they've moved from snake case to camel in a python library 🤯 but it is what it is. I've tested it locally to verify this is correct.

2024-01-16 09:57 UTC, khvn26 approved these changes

2024-01-16 09:59 UTC, merged