chore: Convert environments models TestCase to normal function
SolidStateGroup/bullet-train-api pull request #3442
Opened 2024-02-20 17:02 UTC by zachaysan

Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

I'm working through re-writing the TestCase classes into normal test functions. Rewrote the existing TestCase and replaced with fixtures instead of recreating everything. There are other PRs that are similar to this one.

## How did you test this code?

I manually changed the tests one at a time to refactor them as I went then ran the full test suite afterwards.

2024-02-28 09:34 UTC, gagantrivedi requested changes

2024-02-28 09:34 UTC, gagantrivedi commented on api/tests/unit/environments/test_unit_environments_models.py
> +def test_on_environment_creation_save_feature_states_get_created(
Can we simplify the name of this test? Either remove `creation` or `save`

2024-02-28 19:44 UTC, zachaysan commented on api/tests/unit/environments/test_unit_environments_models.py
> +def test_on_environment_creation_save_feature_states_get_created(
Sure this is done now.

2024-02-29 05:14 UTC, gagantrivedi approved these changes

2024-02-29 10:34 UTC, merged