chore: Show tag usage when deleting
SolidStateGroup/bullet-train-api pull request #3573
Opened 2024-03-06 16:56 UTC by kyle-ssg

Thanks for submitting a PR! Please check the boxes below:

- [x] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Shows when a tag is in use when attempting to delete.

<img width="439" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/8608314/2cb6ba00-b57d-4963-af80-d89a32222a62">

## How did you test this code?

_Please describe._

2024-03-06 18:43 UTC, novakzaballa reviewed
LGTM. However, for example, if I have 2 flags with the same tag, and I remove it from one, the message still says that 2 features are using the tag.

<img width="1004" alt="Screen Shot 2024-03-06 at 14 41 33" src="https://github.com/Flagsmith/flagsmith/assets/41410593/1719eb96-51db-44d0-a444-b04074efb6df">

<img width="675" alt="Screen Shot 2024-03-06 at 14 41 45" src="https://github.com/Flagsmith/flagsmith/assets/41410593/52e09a47-72aa-4fba-b579-3c51cba9610b">

2024-03-13 14:40 UTC, kyle-ssg commented
Thanks for raising @novakzaballa , this is fixed

2024-03-14 13:30 UTC, matthewelwell requested changes
<img width="551" alt="image" src="https://github.com/Flagsmith/flagsmith/assets/14089968/495e2251-312d-444d-9aa8-49422d7a50f1">

🤦

2024-03-14 13:30 UTC, matthewelwell commented on frontend/web/components/TagUsage.tsx
> +        } are using this tag.`}
```suggestion
        warningMessage={`${data?.count} feature${
          data?.count !== 1 ? 's are' : ' is'
        } using this tag.`}
```

2024-03-15 12:09 UTC, matthewelwell approved these changes

2024-03-15 12:12 UTC, merged