docs: fix typo
SolidStateGroup/bullet-train-api pull request #4071
Opened 2024-05-31 20:49 UTC by dabeeeenster

2024-05-31 21:28 UTC, novakzaballa approved these changes
LGTM

2024-05-31 22:31 UTC, matthewelwell requested changes

2024-05-31 22:31 UTC, matthewelwell commented on docs/docs/integrations/project-management/github.md
> +4. Back in Flagsmith application, click on the 'Manage Integration' button.
```suggestion
4. Back in the Flagsmith application, click on the 'Manage Integration' button.
```

2024-06-04 10:08 UTC, matthewelwell approved these changes

2024-06-04 10:09 UTC, merged