deps: bump auth controller
SolidStateGroup/bullet-train-api pull request #4156
Opened 2024-06-13 03:48 UTC by gagantrivedi

- [ ] I have run [`pre-commit`](https://docs.flagsmith.com/platform/contributing#pre-commit) to check linting
- [ ] I have added information to `docs/` if required so people know about the feature!
- [ ] I have filled in the "Changes" section below?
- [ ] I have filled in the "How did you test this code" section below?
- [ ] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Bump auth controller 

## How did you test this code?

Tested in auth controller ci

2024-06-13 08:57 UTC, matthewelwell approved these changes

2024-06-13 10:42 UTC, matthewelwell requested changes
Just realised that I don't think this is correct. There are other locations in the codebase which define this version, e.g. [here](https://github.com/Flagsmith/flagsmith/blob/main/.github/workflows/api-deploy-production-ecs.yml#L40) and [here](https://github.com/Flagsmith/flagsmith/blob/main/.github/workflows/api-deploy-staging-ecs.yml#L41)

2024-06-14 05:01 UTC, gagantrivedi commented
> Just realised that I don't think this is correct. There are other locations in the codebase which define this version, e.g. [here](https://github.com/Flagsmith/flagsmith/blob/main/.github/workflows/api-deploy-production-ecs.yml#L40) and [here](https://github.com/Flagsmith/flagsmith/blob/main/.github/workflows/api-deploy-staging-ecs.yml#L41)

Yep, done

2024-06-14 13:09 UTC, matthewelwell approved these changes

2024-06-14 13:15 UTC, merged