feat: restrict versioning by days
SolidStateGroup/bullet-train-api pull request #4547
Opened 2024-08-28 11:49 UTC by kyle-ssg

Thanks for submitting a PR! Please check the boxes below:

- [x] I have added information to `docs/` if required so people know about the feature!
- [x] I have filled in the "Changes" section below?
- [x] I have filled in the "How did you test this code" section below?
- [x] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

Adjusts limiting of version history to date rather than number of versions

## How did you test this code?

Manually set limitation in code against https://pr-4433-deployment-54847-flagsmith.app.uffizzi.com/

Disabled links in audit log 

![image](https://github.com/user-attachments/assets/aa8b4278-2118-459e-a795-2e72b58935de)

Disabled versions in history 

![image](https://github.com/user-attachments/assets/1860b0bf-0ab3-41d5-a847-21ca25958761)

2024-08-28 14:14 UTC, novakzaballa approved these changes
LGTM from a code perspective

2024-08-28 14:42 UTC, matthewelwell commented
I guess it's good to have the code there, but in theory we should never need the logic to blank out the link from the audit log, because the audit log visibility is also restricted for non-enterprise plans.

2024-08-30 10:17 UTC, matthewelwell commented
Some issues I've found in testing:

1. Since I'm running this self hosted, I would have expected the plan next to 'Version History' to say 'Enterprise' here, like it does for Audit Logs. 

<img width="680" alt="image" src="https://github.com/user-attachments/assets/9fadd4b7-86cc-44ba-941e-2bdb2d944c6e">

<img width="687" alt="image" src="https://github.com/user-attachments/assets/dfec1af4-17c0-4983-850a-2b290161def3">

2. The only time that the API will return versions older than the limit is when the current live version is older than the limit. We shouldn't really blur this out. 

<img width="1227" alt="image" src="https://github.com/user-attachments/assets/3735c1b8-99c3-4039-bf80-5a7f7dbfdb9d">

If we want to blur things out, I could perhaps return a field that states that there are older versions, but I don't think this is necessary. I think we should just let the API handle the restrictions here.

2024-08-30 16:28 UTC, matthewelwell requested changes
See feedback in comment above.

2024-09-10 10:10 UTC, kyle-ssg commented
@matthewelwell this has been resolved

2024-09-10 14:19 UTC, kyle-ssg commented
Note: due to recent PR merge this can now be found within the feature modal 
![image](https://github.com/user-attachments/assets/1497eec8-e5f5-4bf0-94cf-119b9a891f10)

2024-09-10 23:58 UTC, rolodato reviewed
I briefly played around with this but wasn't able to set up a fully representative local environment to test looking at older audit log entries or version history - is there a quick way I could do that?

2024-09-10 23:58 UTC, rolodato commented on frontend/web/components/AuditLog.tsx
> +              <strong>${versionLimitDays} days</strong>.
The wording here could be interpreted as unlocking this specific feature's history and not history on all features - maybe could be reworded as:

> Upgrade to access more than 7 days of feature history.

This avoids using negative terms (lock, limit) in this CTA and is generic enough to work for potential plans that might have more generous, but not unlimited, limits.

2024-09-10 23:58 UTC, rolodato commented on frontend/web/components/AuditLog.tsx
> +              <PlanBasedBanner
I know it's not related to this PR, but this button has too low contrast in dark mode:

![image](https://github.com/user-attachments/assets/a94c734e-237b-4468-9fb3-c90d27d29811)

2024-09-11 13:06 UTC, kyle-ssg commented
> I briefly played around with this but wasn't able to set up a fully representative local environment to test looking at older audit log entries or version history - is there a quick way I could do that?

q for @matthewelwell

2024-09-24 09:43 UTC, kyle-ssg commented
@rolodato resolved button colour in dark mode. I think we're good to go on this ?

2024-10-29 16:14 UTC, matthewelwell commented
> > I briefly played around with this but wasn't able to set up a fully representative local environment to test looking at older audit log entries or version history - is there a quick way I could do that?
> 
> q for @matthewelwell

Sorry @rolodato - I missed this one. The BE has now been merged if that's helpful. In order to manually change the limit though you'll need to directly edit the `organisations_organisationsubscriptioninformationcache` table in the database and set the relevant fields (which should be fairly self explanatory). 

Note that if you're using an organisation on the scale up plan you will also need to set the `VERSIONING_RELEASE_DATE` environment variable in the API to a date in the past to work around the logic which grandfathers unlimited audit log history for existing scale up customers.

2024-10-29 16:23 UTC, matthewelwell approved these changes
This looks good to me from a versioning perspective. 

The only thing I would add is that we should include an upgrade banner on the Audit Log page stating how much Audit Log history the organisation has access to. This is also available in the `audit_log_visibility_days` attribute from the subscription metadata endpoint.

2024-10-30 17:37 UTC, rolodato commented on frontend/web/components/AuditLog.tsx
> +    const date = moment(created_date)
We're parsing `created_date` into a `moment` date here, and also here in `isVersionOverLimit`: https://github.com/Flagsmith/flagsmith/pull/4547/files#diff-e181306c527188403c35874ca85e95550ddaefd2c59a0b3f71dc4603e1a1fd1cR305

2024-11-05 11:29 UTC, matthewelwell approved these changes
Re-tested manually. Looks good to me.

2024-11-05 11:40 UTC, merged