feat: Segment change requests
SolidStateGroup/bullet-train-api pull request #4852
Opened 2024-11-20 13:31 UTC by kyle-ssg

Thanks for submitting a PR! Please check the boxes below:

- [ ] I have added information to `docs/` if required so people know about the feature!
- [ ] I have filled in the "Changes" section below?
- [ ] I have filled in the "How did you test this code" section below?
- [ ] I have used a [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/) title for this Pull Request

## Changes

- Adds change requests for segments
- Moves the change request/requests pages to typescript

## How did you test this code?

_Please describe._

2024-12-18 10:22 UTC, kyle-ssg commented
Awaiting backend fixes

2025-08-26 15:35 UTC, Zaimwa9 requested changes
Big effort thanks.
I've noticed some parts to re-check. I will do another round while testing functionally 👍

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/ProjectChangeRequestsLink.tsx
> +  }
I believe that if we move this flag to ProjectNavBar we could save the above request when deactivated

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/modals/CreateSegment.tsx
> +  const onCreateChangeRequest = (changeRequestData: {
Do you mind switching to async, `.unwrap` the request and add an error message on failure?

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/modals/CreateSegmentRulesTabForm.tsx
> +                  }}
It looks like we can avoid the ternary and have one button:
`onClick={is4eyes ? func : undefined}`maybe have the text in a variable above ?

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/pages/ChangeRequestsPage.tsx
> +  const renderItems = (
Can this be a component ?

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/pages/ProjectChangeRequestPage.tsx
> +            {/*/>*/}
```suggestion
```

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/pages/ProjectChangeRequestPage.tsx
> +const ProjectChangeRequestPage: FC<ProjectChangeRequestPageType> = ({
NIT: sorry if i'm picky, could we rename to `ProjectSingleChangeRequestPage` maybe to mark the difference with the below file

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/pages/ChangeRequestsPage.tsx
> +            <Tabs history={history} urlParam={'tab'}>
And also this history is the global one, Tabs default on history when inside the router which is the case so i think it's safe to remove this one

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/pages/ChangeRequestPage.tsx
> +              <ErrorMessage
I think there's a mismatch with WarningMessage, as warningMessage doesn't exist in this component

2025-08-26 15:35 UTC, Zaimwa9 commented on frontend/web/components/pages/ChangeRequestPage.tsx
> +        )}
Just to confirm it's the permission needed. I have a doubt as it's project level but you know better

2025-08-26 16:05 UTC, kyle-ssg commented on frontend/web/components/pages/ProjectChangeRequestPage.tsx
> +const ProjectChangeRequestPage: FC<ProjectChangeRequestPageType> = ({
Think ProjectChangeRequestDetailPage is a little easier to understand?

2025-08-26 16:25 UTC, kyle-ssg commented on frontend/web/components/pages/ChangeRequestPage.tsx
> +        )}
Wrong file but you're very much correct

2025-08-26 17:24 UTC, Zaimwa9 requested changes
👍  A couple of import cleanup. Otherwise looks good. There is still the ternary. I'd say it's optional++ for easier maintenance later but if you're short on time we can live with it

2025-08-26 17:24 UTC, Zaimwa9 commented on frontend/web/components/diff/DiffSegment.tsx
> +import { Tab } from '@material-ui/core'
```suggestion
```

2025-08-26 17:24 UTC, Zaimwa9 commented on frontend/web/components/ExistingProjectChangeRequestAlert.tsx
> +  useGetProjectChangeRequestsQuery,
```suggestion
```

2025-08-26 17:24 UTC, Zaimwa9 commented on frontend/web/components/ExistingProjectChangeRequestAlert.tsx
> +import { useGetChangeRequestsQuery } from 'common/services/useChangeRequest'
```suggestion
```

2025-09-03 10:04 UTC, Zaimwa9 approved these changes

2025-09-03 10:07 UTC, matthewelwell approved these changes
Approving based on the fact that @Zaimwa9 has approved, but since he's made some (very minor) changes, his approval is insufficient to be able to merge.

2025-09-03 12:01 UTC, merged