feature/static-folder-for-frontend
SolidStateGroup/bullet-train-api pull request #803
Opened 2022-02-21 11:34 UTC by dabeeeenster

2022-02-21 11:49 UTC, kyle-ssg requested changes
Needs plugins.js/webpack.config.django.prod.js to be adjusted, needs testing with npm run bundle and npm start

2022-02-21 11:53 UTC, kyle-ssg commented
> Needs plugins.js/webpack.config.django.prod.js to be adjusted, needs testing with npm run bundle and npm start

![image](https://user-images.githubusercontent.com/8608314/154950341-8e3c9f46-f384-49a9-b097-b78789a8f7cb.png)

2022-02-21 14:46 UTC, dabeeeenster commented
> Needs plugins.js/webpack.config.django.prod.js to be adjusted, needs testing with npm run bundle and npm start

This is fixed - tested and working here - also the django AIO image is working now too.

2022-02-21 16:30 UTC, matthewelwell approved these changes
Looks good to me.

2022-02-21 16:30 UTC, matthewelwell commented on frontend/web/components/LegalAside.js
> -                <h3 className="link-header">Agreeements</h3>
Lol

2022-02-21 16:37 UTC, dabeeeenster commented on frontend/web/components/LegalAside.js
> -                <h3 className="link-header">Agreeements</h3>
The quality was immense in 2017

2022-02-22 09:04 UTC, kyle-ssg approved these changes

2022-02-22 09:29 UTC, merged